### PR TITLE
Fix build warnings

### LINKED ISSUE #24: GIR generation: app-indicator.c:576: Warning: AyatanaAppIndicator3: incorrect number of parameters in comment block, parameter annotations will be ignored
```
[ 21%] Generating AyatanaAppIndicator3-0.1.gir
cd /home/sunweaver/MyDocuments/4projects/ayatana-upstream/libayatana-appindicator.upstream/libayatana-appindicator/src && /usr/bin/g-ir-scanner app-indicator.c app-indicator.h --add-include-path=/home/sunweaver/MyDocuments/4projects/ayatana-upstream/libayatana-appindicator.upstream/libayatana-appindicator/build/gtk3/src --c-include=libayatana-appindicator/app-indicator.h --symbol-prefix=app --identifier-prefix=App --namespace=AyatanaAppIndicator3 --nsversion=0.1 --quiet --warn-all --include=GObject-2.0 --include=Gtk-3.0 --library-path=/home/sunweaver/MyDocuments/4projects/ayatana-upstream/libayatana-appindicator.upstream/libayatana-appindicator/build/gtk3/src --library="ayatana-appindicator3" --output /home/sunweaver/MyDocuments/4projects/ayatana-upstream/libayatana-appindicator.upstream/libayatana-appindicator/build/gtk3/src/AyatanaAppIndicator3-0.1.gir
app-indicator.h:76: Warning: AyatanaAppIndicator3: symbol='IS_APP_INDICATOR': Unknown namespace for symbol 'IS_APP_INDICATOR'
app-indicator.h:77: Warning: AyatanaAppIndicator3: symbol='IS_APP_INDICATOR_CLASS': Unknown namespace for symbol 'IS_APP_INDICATOR_CLASS'
app-indicator.c:576: Warning: AyatanaAppIndicator3: incorrect number of parameters in comment block, parameter annotations will be ignored.
```

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/AyatanaIndicators/libayatana-appindicator/issues/24

@sunweaver I would like to have this merged and continue fixing it in a later pull request to avoid making a mess.

### CODE REVIEW

File: src/app-indicator.c [hunk 1]
```diff
@@ -578,6 +578,7 @@ app_indicator_class_init (AppIndicatorClass *klass)
     /**
      * AppIndicator::new-icon-theme-path:
      * @arg0: The #AppIndicator object
+     * @arg1: The icon theme path
```
Comment (sunweaver) [inline src/app-indicator.c:581]: Where does this come from in this commit? Maybe have a separate commit for this with more explanatory text in the commit message? Has it been forgotten, so far? etc.

File: bindings/vala/ayatana-appindicator-0.1-custom.vala [hunk 2]
```diff
@@ -19,11 +20,13 @@
...
 
-  Authored by Michal Hruby <michal.hruby@canonical.com>
+  Authors:
+      Michal Hruby <michal.hruby@canonical.com>
+      Robert Tari <robert@tari.in>
 */
 
 namespace AppIndicator {
-  [CCode (type_check_function = "IS_APP_INDICATOR", type_id = "app_indicator_get_type ()")]
+  [CCode (type_check_function = "APP_IS_INDICATOR", type_id = "app_indicator_get_type ()")]
```
Comment (sunweaver) [inline bindings/vala/ayatana-appindicator-0.1-custom.vala:29]: Urgh, don't we introduce an API change with this? Maybe we need some IS_APP_INDICATOR = APP_IS_INDICATOR somewhere?

Why the renaming at all???

File: src/app-indicator.c [hunk 3]
```diff
@@ -1998,7 +1999,7 @@ app_indicator_set_icon (AppIndicator *self, const gchar *icon_name)
  * app_indicator_set_icon_full:
  * @self: The #AppIndicator object to use
  * @icon_name: The icon name to set.
- * @icon_desc: A textual description of the icon for accessibility
+ * @icon_desc: (nullable): A textual description of the icon for accessibility
```
Comment (sunweaver) [inline src/app-indicator.c:2002]: Maybe ship this in a separate commit?

File: src/app-indicator.h [hunk 4]
```diff
@@ -73,8 +73,8 @@ G_BEGIN_DECLS
 #define APP_INDICATOR_TYPE            (app_indicator_get_type ())
 #define APP_INDICATOR(obj)            (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_INDICATOR_TYPE, AppIndicator))
 #define APP_INDICATOR_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST ((klass), APP_INDICATOR_TYPE, AppIndicatorClass))
-#define IS_APP_INDICATOR(obj)         (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_INDICATOR_TYPE))
-#define IS_APP_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_INDICATOR_TYPE))
+#define APP_IS_INDICATOR(obj)         (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_INDICATOR_TYPE))
+#define APP_IS_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_INDICATOR_TYPE))
```
Comment (sunweaver) [inline src/app-indicator.h:77]: I don't like this renaming as it looks like it will break compat with libappindicator (without much gain except a cosmetic one).

**Review by sunweaver — CHANGES_REQUESTED** [review]
I don't see the point in renaming APP_IS_INDICATOR / IS_APP_INDICATOR. Personally, it seems that IS_APP_INDICATOR is the better phrase anyway.

We will certainly break API with this, so we should not have this renaming, IMHO.

**Comment by ghost** [comment]
> I don't see the point in renaming APP_IS_INDICATOR / IS_APP_INDICATOR. Personally, it seems that IS_APP_INDICATOR is the better phrase anyway.
> 
> We will certainly break API with this, so we should not have this renaming, IMHO.

This is the proper name of the macro when creating GObject C subclasses, it's internal to the class. Somebody mistakenly swapped the `IS_` part a long time ago. The build also complains about it.

https://wiki.gnome.org/HowDoI/SubclassGObject

While we have IS_APP_INDICATOR, we must consider the code malformed and broken. It's a miracle the other macros only throw warnings.

**Review by sunweaver — APPROVED** [review]
LGTM now, let's have it.
